// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqH9KhWgPHc2a1ZR2zBTIPrOqtGGC41I',
    appId: '1:190569139844:web:6f658eb4ee4b2c1c8dbcd1',
    messagingSenderId: '190569139844',
    projectId: 'appsetup-781df',
    authDomain: 'appsetup-781df.firebaseapp.com',
    storageBucket: 'appsetup-781df.firebasestorage.app',
    measurementId: 'G-6LTPBMJ4XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTmUO833BVDkG1pnkzkGGcxMWFmJWaLY',
    appId: '1:190569139844:android:5aa716ddf54bc61a8dbcd1',
    messagingSenderId: '190569139844',
    projectId: 'appsetup-781df',
    storageBucket: 'appsetup-781df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbnmOc9ShQq1VMNHogRlrXIhP3dpxwizg',
    appId: '1:190569139844:ios:081cf0d9c6ef7f268dbcd1',
    messagingSenderId: '190569139844',
    projectId: 'appsetup-781df',
    storageBucket: 'appsetup-781df.firebasestorage.app',
    iosBundleId: 'com.appseba.appsetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbnmOc9ShQq1VMNHogRlrXIhP3dpxwizg',
    appId: '1:190569139844:ios:6febbdb1619c62468dbcd1',
    messagingSenderId: '190569139844',
    projectId: 'appsetup-781df',
    storageBucket: 'appsetup-781df.firebasestorage.app',
    iosBundleId: 'com.example.setupapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqH9KhWgPHc2a1ZR2zBTIPrOqtGGC41I',
    appId: '1:190569139844:web:fd8608f87ade697b8dbcd1',
    messagingSenderId: '190569139844',
    projectId: 'appsetup-781df',
    authDomain: 'appsetup-781df.firebaseapp.com',
    storageBucket: 'appsetup-781df.firebasestorage.app',
    measurementId: 'G-P76YPS3SK2',
  );
}
